#!/usr/bin/bash

systemctl --user import-environment
systemctl --user start sway-session.target

gnome='org.gnome.desktop.interface'

gsettings set $gnome gtk-theme 'Adwaita-dark'
gsettings set $gnome font-name 'Sans 10'

