#!/usr/bin/env bash

type stow &>/dev/null || {
  echo >&2 "GNU stow is not installed"
  exit 1
}

base="$(dirname "$(readlink -f "$0")")"

find "$base" -maxdepth 1 -type d ! -path "$base" ! -path '*/\.*' -execdir \
  bash -c 'stow --verbose --adopt --target="$HOME" --restow "$(basename "$0")"' {} ';'

